## Loading Data 2010-2021

In [70]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# loading data
df = pd.read_csv("../CSV/2010-2021.csv")
# drop unused columns
df.drop('LOWEST SALE PRICE', axis=1, inplace=True)
df.drop('HIGHEST SALE PRICE', axis=1, inplace=True)
# create grouping of data using specified column then
# creates a copy of specified entry within the column group
manhattan = groupby_borough = df.groupby(['BOROUGH']).get_group(('MANHATTAN',)).copy()

# group further by home type
groupby_home = manhattan.groupby(['TYPE OF HOME'])
one = groupby_home.get_group(('01 ONE FAMILY HOMES',)).copy()
two = groupby_home.get_group(('02 TWO FAMILY HOMES',)).copy()
three = groupby_home.get_group(('03 THREE FAMILY HOMES',)).copy()

## Setting up Model

In [71]:
# group home type into neighborhood
hood_names_one = one['NEIGHBORHOOD'].unique()
hood_names_two = two['NEIGHBORHOOD'].unique()
hood_names_three = three['NEIGHBORHOOD'].unique()

# get unique neighborhood names
groupby_hood_one = one.groupby(['NEIGHBORHOOD'])
groupby_hood_two = two.groupby(['NEIGHBORHOOD'])
groupby_hood_three = three.groupby(['NEIGHBORHOOD'])

# run the code using print(h) to get problem data and we hard code this
# this way the CVS file doesn't get modified continuously
# not enough data, to split the data 80/20
small_sample_one = ["FASHION", "FLATIRON"] 
small_sample_two = ["CHINATOWN", "JAVITS CENTER", "LITTLE ITALY"] 
small_sample_three = ["MIDTOWN WEST", "HARLEM-WEST"] 

# prediction model - ONE
dic_one = {}
for h in hood_names_one:
    temp = groupby_hood_one.get_group((h,)).copy()
    # print(h)
    if h in small_sample_one:
        dic_one[h] = temp['AVERAGE SALE PRICE'].item()
    else:
        X = temp[['YEAR', 'MEDIAN SALE PRICE', 'NUMBER OF SALES']] # independent variables table
        y = temp['AVERAGE SALE PRICE']
    
        # split the data 80/20
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
    
        # fit model
        model = LinearRegression()
        model.fit(X_train, y_train)
        
        # compare to test data
        y_pred = model.predict(X_test)
        dic_one[h] = y_pred[0]


# prediction model - TWO
dic_two = {}
for h in hood_names_two:
    temp = groupby_hood_two.get_group((h,)).copy()
    # print(h)
    if h in small_sample_two:
        dic_two[h] = temp['AVERAGE SALE PRICE'].item()
    else:
        X = temp[['YEAR', 'MEDIAN SALE PRICE', 'NUMBER OF SALES']]
        y = temp['AVERAGE SALE PRICE']
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
        model = LinearRegression()
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        dic_two[h] = y_pred[0]


# prediction model - THREE
dic_three = {}
for h in hood_names_three:
    temp = groupby_hood_three.get_group((h,)).copy()
    # print(h)
    if h in small_sample_three:
        dic_three[h] = temp['AVERAGE SALE PRICE'].item()
    else:
        X = temp[['YEAR', 'MEDIAN SALE PRICE', 'NUMBER OF SALES']]
        y = temp['AVERAGE SALE PRICE']
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
        model = LinearRegression()
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        dic_three[h] = y_pred[0]

## Comparing Model to Data 2022

In [84]:
# loading real data
df22 = pd.read_csv("../CSV/2022.csv")
df22.drop('NUMBER OF SALES', axis=1, inplace=True)
df22.drop('LOWEST SALE PRICE', axis=1, inplace=True)
df22.drop('MEDIAN SALE PRICE', axis=1, inplace=True)
df22.drop('HIGHEST SALE PRICE', axis=1, inplace=True)
df22.drop('YEAR', axis=1, inplace=True)
test = groupby_borough = df22.groupby(['BOROUGH']).get_group(('MANHATTAN',)).copy()
test.drop('BOROUGH', axis=1, inplace=True)
test

                  NEIGHBORHOOD           TYPE OF HOME  AVERAGE SALE PRICE
263              ALPHABET CITY    01 ONE FAMILY HOMES              399000
264              ALPHABET CITY    02 TWO FAMILY HOMES             2999999
265                    CHELSEA    01 ONE FAMILY HOMES             7282668
266                    CHELSEA    02 TWO FAMILY HOMES             5300000
267                    CHELSEA  03 THREE FAMILY HOMES             3975000
268                    CLINTON    01 ONE FAMILY HOMES             3300000
269                    CLINTON    02 TWO FAMILY HOMES             3415000
270                   GRAMERCY    02 TWO FAMILY HOMES             6666667
271  GREENWICH VILLAGE-CENTRAL    01 ONE FAMILY HOMES            35000000
272  GREENWICH VILLAGE-CENTRAL    02 TWO FAMILY HOMES             6904167
273  GREENWICH VILLAGE-CENTRAL  03 THREE FAMILY HOMES             9300000
274     GREENWICH VILLAGE-WEST    01 ONE FAMILY HOMES             9603400
275     GREENWICH VILLAGE-WEST    02 TWO FAMILY HOMES            11422222
276     GREENWICH VILLAGE-WEST  03 THREE FAMILY HOMES             7481250
277             HARLEM-CENTRAL    01 ONE FAMILY HOMES             2960797
278             HARLEM-CENTRAL    02 TWO FAMILY HOMES             2638077
279             HARLEM-CENTRAL  03 THREE FAMILY HOMES             2238447
280                HARLEM-EAST    01 ONE FAMILY HOMES             4556900
281                HARLEM-EAST    02 TWO FAMILY HOMES              901221
282                HARLEM-EAST  03 THREE FAMILY HOMES             1300000
283               HARLEM-UPPER    01 ONE FAMILY HOMES             3039500
284               HARLEM-UPPER    02 TWO FAMILY HOMES             2940083
285               HARLEM-UPPER  03 THREE FAMILY HOMES             1404333
286                     INWOOD    01 ONE FAMILY HOMES              896000
287                     INWOOD    02 TWO FAMILY HOMES             1222000
288                   KIPS BAY    02 TWO FAMILY HOMES             3445325
289               LITTLE ITALY    01 ONE FAMILY HOMES             5950000
290           MANHATTAN VALLEY    01 ONE FAMILY HOMES             3725000
291           MANHATTAN VALLEY    02 TWO FAMILY HOMES             3525000
292               MIDTOWN EAST    01 ONE FAMILY HOMES             6098358
293               MIDTOWN EAST    02 TWO FAMILY HOMES             7275000
294               MIDTOWN EAST  03 THREE FAMILY HOMES             4750000
295                MURRAY HILL    01 ONE FAMILY HOMES             4393750
296                MURRAY HILL    02 TWO FAMILY HOMES             4117667
297                       SOHO    01 ONE FAMILY HOMES            14800000
298                       SOHO    02 TWO FAMILY HOMES             6000000
299                       SOHO  03 THREE FAMILY HOMES             7200000
300                SOUTHBRIDGE    01 ONE FAMILY HOMES             3500000
301                    TRIBECA    01 ONE FAMILY HOMES            10223750
302    UPPER EAST SIDE (59-79)    01 ONE FAMILY HOMES            15599082
303    UPPER EAST SIDE (59-79)    02 TWO FAMILY HOMES            10523056
304    UPPER EAST SIDE (59-79)  03 THREE FAMILY HOMES            27000000
305    UPPER EAST SIDE (79-96)    01 ONE FAMILY HOMES            10650618
306    UPPER EAST SIDE (79-96)    02 TWO FAMILY HOMES             8500000
307    UPPER EAST SIDE (79-96)  03 THREE FAMILY HOMES            11400000
308    UPPER WEST SIDE (59-79)    01 ONE FAMILY HOMES            11226805
309    UPPER WEST SIDE (59-79)    02 TWO FAMILY HOMES             5715000
310    UPPER WEST SIDE (79-96)    01 ONE FAMILY HOMES            11082742
311    UPPER WEST SIDE (79-96)    02 TWO FAMILY HOMES             5026084
312    UPPER WEST SIDE (79-96)  03 THREE FAMILY HOMES             6162500
313   WASHINGTON HEIGHTS LOWER    01 ONE FAMILY HOMES             1981404
314   WASHINGTON HEIGHTS LOWER    02 TWO FAMILY HOMES             1870742
315   WASHINGTON HEIGHTS LOWER  03 THREE FAMILY HOMES             1551335
316   WASHINGTON HEIGHTS UPPER    01 ONE FAMILY HOMES             1250000

In [85]:
test['PREDICT'] = "-"
test['DELTA'] = "0"

# use 3 conditionals because not all targeted neighborhoods from the 2022 may appear in 2010-2021
for i, row in test.iterrows():
    if row['TYPE OF HOME'] == '01 ONE FAMILY HOMES' and row['NEIGHBORHOOD'] in dic_one:
        test.at[i, 'PREDICT'] = int(dic_one[row['NEIGHBORHOOD']])
        test.at[i, 'DELTA'] = int(row['AVERAGE SALE PRICE']) - int(dic_one[row['NEIGHBORHOOD']])
    elif row['TYPE OF HOME'] == '02 TWO FAMILY HOMES' and row['NEIGHBORHOOD'] in dic_two:
        test.at[i, 'PREDICT'] = int(dic_two[row['NEIGHBORHOOD']])
        test.at[i, 'DELTA'] = int(row['AVERAGE SALE PRICE']) - int(dic_two[row['NEIGHBORHOOD']])
    elif row['TYPE OF HOME'] == '03 THREE FAMILY HOMES' and row['NEIGHBORHOOD'] in dic_three:
        test.at[i, 'PREDICT'] = int(dic_three[row['NEIGHBORHOOD']])
        test.at[i, 'DELTA'] = int(row['AVERAGE SALE PRICE']) - int(dic_three[row['NEIGHBORHOOD']])

In [86]:
test

,NEIGHBORHOOD,TYPE OF HOME,AVERAGE SALE PRICE,PREDICT,DELTA
263,ALPHABET CITY,01 ONE FAMILY HOMES,399000,5472405,-5073405
264,ALPHABET CITY,02 TWO FAMILY HOMES,2999999,3024999,-25000
265,CHELSEA,01 ONE FAMILY HOMES,7282668,4747177,2535491
266,CHELSEA,02 TWO FAMILY HOMES,5300000,6433367,-1133367
267,CHELSEA,03 THREE FAMILY HOMES,3975000,4813492,-838492
268,CLINTON,01 ONE FAMILY HOMES,3300000,3850000,-550000
269,CLINTON,02 TWO FAMILY HOMES,3415000,5699999,-2284999
270,GRAMERCY,02 TWO FAMILY HOMES,6666667,374876,6291791
271,GREENWICH VILLAGE-CENTRAL,01 ONE FAMILY HOMES,35000000,15584426,19415574
272,GREENWICH VILLAGE-CENTRAL,02 TWO FAMILY HOMES,6904167,10050000,-3145833
273,GREENWICH VILLAGE-CENTRAL,03 THREE FAMILY HOMES,9300000,7900000,1400000
274,GREENWICH VILLAGE-WEST,01 ONE FAMILY HOMES,9603400,8872090,731310
275,GREENWICH VILLAGE-WEST,02 TWO FAMILY HOMES,11422222,9025096,2397126
276,GREENWICH VILLAGE-WEST,03 THREE FAMILY HOMES,7481250,8385308,-904058
277,HARLEM-CENTRAL,01 ONE FAMILY HOMES,2960797,2173006,787791
278,HARLEM-CENTRAL,02 TWO FAMILY HOMES,2638077,2081572,556505
279,HARLEM-CENTRAL,03 THREE FAMILY HOMES,2238447,2939700,-701253
280,HARLEM-EAST,01 ONE FAMILY HOMES,4556900,3516790,1040110
281,HARLEM-EAST,02 TWO FAMILY HOMES,901221,1194493,-293272
282,HARLEM-EAST,03 THREE FAMILY HOMES,1300000,2040277,-740277
283,HARLEM-UPPER,01 ONE FAMILY HOMES,3039500,2664754,374746
284,HARLEM-UPPER,02 TWO FAMILY HOMES,2940083,1727698,1212385
285,HARLEM-UPPER,03 THREE FAMILY HOMES,1404333,1519494,-115161
286,INWOOD,01 ONE FAMILY HOMES,896000,725638,170362
287,INWOOD,02 TWO FAMILY HOMES,1222000,434910,787090
288,KIPS BAY,02 TWO FAMILY HOMES,3445325,9344475,-5899150
289,LITTLE ITALY,01 ONE FAMILY HOMES,5950000,9700000,-3750000
290,MANHATTAN VALLEY,01 ONE FAMILY HOMES,3725000,3750000,-25000
291,MANHATTAN VALLEY,02 TWO FAMILY HOMES,3525000,3500000,25000
292,MIDTOWN EAST,01 ONE FAMILY HOMES,6098358,6477447,-379089
293,MIDTOWN EAST,02 TWO FAMILY HOMES,7275000,4875000,2400000
294,MIDTOWN EAST,03 THREE FAMILY HOMES,4750000,319393,4430607
295,MURRAY HILL,01 ONE FAMILY HOMES,4393750,4200710,193040
296,MURRAY HILL,02 TWO FAMILY HOMES,4117667,5800102,-1682435
297,SOHO,01 ONE FAMILY HOMES,14800000,5892535,8907465
298,SOHO,02 TWO FAMILY HOMES,6000000,14242607,-8242607
299,SOHO,03 THREE FAMILY HOMES,7200000,-57017876,64217876
300,SOUTHBRIDGE,01 ONE FAMILY HOMES,3500000,5250000,-1750000
301,TRIBECA,01 ONE FAMILY HOMES,10223750,10731015,-507265
302,UPPER EAST SIDE (59-79),01 ONE FAMILY HOMES,15599082,14150381,1448701
303,UPPER EAST SIDE (59-79),02 TWO FAMILY HOMES,10523056,11494961,-971905
304,UPPER EAST SIDE (59-79),03 THREE FAMILY HOMES,27000000,5350000,21650000
305,UPPER EAST SIDE (79-96),01 ONE FAMILY HOMES,10650618,10310507,340111
306,UPPER EAST SIDE (79-96),02 TWO FAMILY HOMES,8500000,10914781,-2414781
307,UPPER EAST SIDE (79-96),03 THREE FAMILY HOMES,11400000,6616767,4783233
308,UPPER WEST SIDE (59-79),01 ONE FAMILY HOMES,11226805,9953798,1273007
309,UPPER WEST SIDE (59-79),02 TWO FAMILY HOMES,5715000,5775319,-60319
310,UPPER WEST SIDE (79-96),01 ONE FAMILY HOMES,11082742,7792719,3290023
311,UPPER WEST SIDE (79-96),02 TWO FAMILY HOMES,5026084,7085101,-2059017
312,UPPER WEST SIDE (79-96),03 THREE FAMILY HOMES,6162500,7801180,-1638680
313,WASHINGTON HEIGHTS LOWER,01 ONE FAMILY HOMES,1981404,1441192,540212
314,WASHINGTON HEIGHTS LOWER,02 TWO FAMILY HOMES,1870742,902210,968532
315,WASHINGTON HEIGHTS LOWER,03 THREE FAMILY HOMES,1551335,2358749,-807414
316,WASHINGTON HEIGHTS UPPER,01 ONE FAMILY HOMES,1250000,1275000,-25000

## Reflection
The model's accuracy is limited. Manhattan properties exhibit a wide price range, with some homes selling for as much as 100 million and others for under 1 million. Additionally, the data sample size is insufficient, leading to skewed results in certain cases. It is hoped that models for other boroughs will be more accurate, given the larger volume of available data and the generally more affordable property prices.